#!/bin/sh
#Get full time and turn it into a sting array
f=`getTime | tail -n 1`
IFS=' '
read -a fu <<< "$f"
#Determine month
months=("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec")
ns=(01 02 03 04 05 06 07 08 09 10 11 12)
for (( i=0; $i<=${#months[*]}; i++ ));
do
	if [[ ${fu[1]} = ${months[${i}]} ]]; then
		m=${ns[${i}]}
	fi
done
fd="${fu[5]}-${m}-${fu[2]} ${fu[3]}"
timedatectl set-time "${fd}"
